# Generated by Django 4.2.13 on 2024-07-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
